version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "a meaningful change"
  test:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "change 2 on dev_test branch"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test
